version: "3.5"

services:
  chronograf:
    image: chronograf:latest
    container_name: chronograf
    hostname: chronograf
    ports:
      - 8888:8888
    restart: unless-stopped
    networks:
      - influxdb-cluster

networks:
  influxdb-cluster: