version: "3.5"

services:
  influxdb-admin:
    image: influxtsdb/influxdb-admin:latest
    container_name: influxdb-admin
    hostname: influxdb-admin
    ports:
      - 8083:8083
    restart: unless-stopped
    networks:
      - influxdb-cluster

networks:
  influxdb-cluster: