version: "3.5"

services:
  telegraf:
    image: telegraf:1.27.2
    container_name: telegraf
    restart: unless-stopped
    ports:
      - "8092:8092/udp"
      - 8094:8094
      - "8125:8125/udp"
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
      HOST_VAR: /hostfs/var
      HOST_RUN: /hostfs/run
      HOST_MOUNT_PREFIX: /hostfs
    volumes:
     - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /sys:/rootfs/sys:ro
     - /proc:/rootfs/proc:ro
     - /etc:/rootfs/etc:ro
    networks:
      - influxdb-cluster

networks:
  influxdb-cluster: